WITH source AS (
    SELECT * FROM {{ source('tesla', 'records') }}
),

renamed AS (
    SELECT
        region,
        CASE region
            WHEN 'uswe2' THEN 'US'
            WHEN 'apse2' THEN 'AU'
            WHEN 'euce1' THEN 'EU'
            WHEN 'apne1' THEN 'JP'
            WHEN 'apse1' THEN 'SG'
            WHEN 'cace1' THEN 'CA'
            ELSE 'Unknown'
        END AS region_simplify,
        CAST(_id AS STRING)                       AS record_id,
        CAST(facility_id AS STRING)               AS facility_id,
        CAST(team_id AS STRING)                   AS team_id,
        CAST(user_id AS STRING)                   AS user_id,
        CAST(editor_id AS STRING)                 AS editor_id,
        CAST(workspace_id AS STRING)              AS workspace_id,
        CAST(storage_id AS STRING)                AS storage_id,
        CAST(last_updated_user_id AS STRING)      AS last_updated_user_id,
        CAST(cycle_state_updated_by_id AS STRING) AS cycle_state_updated_by_id,
        CAST(last_billing_model_id AS STRING)     AS last_billing_model_id,
        uuid,
        ifc_guid,
        note,
        description,
        priority,
        state,
        cycle_state,
        capture_editing_state,
        fresh_state,
        action_state,
        running_state,
        siteinsights_report_state,
        error_code,
        cached,
        thumbnail,
        voxels,
        content_url_type,
        last_billing_model_type,
        sf_resource_id,
        opt_out,
        pointclouds_count,
        meshes_count,
        credit_transactions_count,
        captures_count,
        jobs_count,
        TIMESTAMP(created_at)                            AS created_at,
        TIMESTAMP(updated_at)                            AS updated_at,
        TIMESTAMP(captured_at)                           AS captured_at,
        TIMESTAMP(siteinsights_published_at)             AS siteinsights_published_at,
        TIMESTAMP(siteinsights_report_state_updated_at)  AS siteinsights_report_state_updated_at,
        TIMESTAMP(cycle_state_updated_at)                AS cycle_state_updated_at,
        TIMESTAMP(capture_editing_state_updated_at)      AS capture_editing_state_updated_at,
        TIMESTAMP(fresh_state_updated_at)                AS fresh_state_updated_at,
        TIMESTAMP(action_state_updated_at)               AS action_state_updated_at,
        TIMESTAMP(charge_credit_after_at)                AS charge_credit_after_at,
        TIMESTAMP(cleaned_at)                            AS cleaned_at,
        TIMESTAMP(purged_at)                             AS purged_at,
        TIMESTAMP(trashed_at)                            AS trashed_at,
        meta,
        qa_preference,
        sys,
        tenant
    FROM source
),

final AS (
    SELECT
        region,
        region_simplify,
        record_id,
        CONCAT(region_simplify, '-', record_id, '-', tenant)   AS region_record_id,
        facility_id,
        CONCAT(region_simplify, '-', facility_id, '-', tenant) AS region_facility_id,
        team_id,
        CONCAT(region_simplify, '-', team_id, '-', tenant)     AS region_team_id,
        user_id,
        editor_id,
        workspace_id,
        storage_id,
        last_updated_user_id,
        cycle_state_updated_by_id,
        last_billing_model_id,
        uuid,
        ifc_guid,
        note,
        description,
        priority,
        state,
        cycle_state,
        capture_editing_state,
        fresh_state,
        action_state,
        running_state,
        siteinsights_report_state,
        error_code,
        cached,
        thumbnail,
        voxels,
        content_url_type,
        last_billing_model_type,
        sf_resource_id,
        opt_out,
        pointclouds_count,
        meshes_count,
        credit_transactions_count,
        captures_count,
        jobs_count,
        created_at,
        updated_at,
        captured_at,
        siteinsights_published_at,
        siteinsights_report_state_updated_at,
        cycle_state_updated_at,
        capture_editing_state_updated_at,
        fresh_state_updated_at,
        action_state_updated_at,
        charge_credit_after_at,
        cleaned_at,
        purged_at,
        trashed_at,
        meta,
        qa_preference,
        sys,
        tenant
    FROM renamed
)

SELECT * FROM final
